# Generated by Django 4.2.14 on 2024-07-30 16:54

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('photo', models.FileField(blank=True, null=True, upload_to='team')),
                ('job', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('تیم فنی', 'تیم فنی'), ('تیم تولید محتوا', 'تیم تولید محتوا'), ('تیم مارکتینگ و روابط عمومی', 'تیم مارکتینگ و روابط عمومی'), ('تیم عکاسی و فیلم برداری', 'تیم عکاسی و فیلم برداری'), ('تیم اجرایی', 'تیم اجرایی')], max_length=100, verbose_name='تیم')),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='team/social')),
                ('alt', models.CharField(max_length=300)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
